PX4/NuttX branch test: master
NuttX:
 - https://github.com/PX4-NuttX/nuttx/tree/master
 - https://github.com/PX4-NuttX/nuttx/commit/27aa16111cc2934cf214ca9e976d0d57f5e02a4f

Changes from PX4/NuttX (https://github.com/PX4/NuttX/commit/b902d4ca3d79ffbd5148670cb13bfeef7d917555) in current PX4/master (44bec269b0313c1644f9ad1335e768bb9a36f0b3)
https://github.com/PX4/NuttX/compare/b902d4ca3d79ffbd5148670cb13bfeef7d917555...27aa16111cc2934cf214ca9e976d0d57f5e02a4f

27aa16111c (HEAD, origin/master) sim: hostfs: Stop assuming CONFIG_NAME_MAX=32
f89ccf873e sim: host_readdir: Ensure NUL termination when truncating d_name
c65bdde5ac include/nuttx/fs/hostfs.h: Appease nxstyle errors
3ff956dc00 stm32h7: support SDRAM via FMC peripherial (#459)
2991836ee8 sim: Appease nxstyle errors
f19355132a sim: Mention vpnkit docker image
3f860280e5 arm/common: Fix nxstyle issue in arch/arm/src/common/up_checkstack.c
bc29b25983 arm/imx6: compile up_hostfs.c when CONFIG_ARM_SEMIHOSTING_HOSTFS equal true
d5905d5963 arch/arm: Fix linker error: undefined reference to `g_intstackalloc'
272a1460c5 Revert "tools/testbuild.sh: suppress lots of stdout log from configure.sh"

Apps:
 - https://github.com/PX4/NuttX-apps/tree/master
 - https://github.com/PX4/NuttX-apps/commit/f16a765ccaa9395250423c4498a9e31aac5a558d

Changes from PX4/NuttX-apps (https://github.com/PX4/NuttX-apps/commit/91b6ad6a0d00ac107088b18588cd54d40e3cb796) in current PX4/master (44bec269b0313c1644f9ad1335e768bb9a36f0b3)
https://github.com/PX4/NuttX-apps/compare/91b6ad6a0d00ac107088b18588cd54d40e3cb796...f16a765ccaa9395250423c4498a9e31aac5a558d

f16a765c (HEAD -> master, origin/master) examples: Fix the parallel build break (#138)
1511403f Revert "Don't generate .depend anymore"
f074d7f3 Makefile: let install depend on the target binary
258e0140 Revert "Ensure "build" before "install""
8a7ea169 Revert "examples/elf/tests: Ensure "build" before "install""
9394424b Revert "examples/sotest/lib: Fix dependency"
cc5ad09c Don't generate .depend anymore
6ddf3471 Move MAKE_template and SDIR_template to Make.defs (#135)
6e3a9a2e Call TESTANDREPLACEFILE instead of mv
7caef179 Fix the typo error